### PR TITLE
(wip) a-24

### PR DESCRIPTION
**Pull request by udeved**

### CODE REVIEW

**Review by StanleySweet — CHANGES_REQUESTED** [review]
Can you use two spaces (no tabs) instead of four spaces tabs for XML files? That's the convention, and what XML exporters usually do. I'm guilty for trying to change that some time ago

**Comment by udeved** [comment]
Hmm, I could, however, 2 spaces directly clashed with all my other linux projects which use usually 4 spaces default.
I would have to set it every time I work on the mod to two spaces, which is not a viable option.
My proposal is, it will be formatted before a new point release.
There are still xml files in there which likely have broken or bad xml, passed validation, but effectively broke nodes.
My worry is more having proper xml.

**Comment by StanleySweet** [comment]
The game deals fine with four spaces. The only thing that does two spaces is the official tool to edit actor files, and the C# tool I made. As well as ETREE (Python).

So I guess it can stay four spaces if you really need it.

**Comment by StanleySweet** [comment]
To test for broken XML you can use the map Units_Demo

**Comment by StanleySweet** [comment]
There is also the validate cmdline option :)

**Comment by udeved** [comment]
As long as game engine doesn't expect explicit xml indention, all good then. :)

4 spaces help me to kill wrong indent in many xml files, mixed tabs and spaces become visible easily.

**Pull request merged**
